
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

interface InterfaceGameObject {
    function attackBase(uint attack) external returns(string);
    function attackWarrior(uint attack) external returns(string);
    function attackArcher(uint attack) external returns(string);
    function destroy(address) external;
}