
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "gameObject.sol";

contract militaryUnit is gameObject {

    uint warriorAttack = 3;
    uint archerAttack = 2;
    address baseAddr; 


    function attackEnemy(InterfaceGameObject enemyAddr, string unitType, uint attackPower) public {
        if (unitType == "base") {
            enemyAddr.attackBase(attackPower);
        } else if (unitType == "warrior"){
            enemyAddr.attackWarrior(attackPower);
        } else if (unitType == "archer"){
            enemyAddr.attackWarrior(attackPower);
        }
        
    }

    function getAttackPower() virtual public view returns (string, uint){
        return("Warrior attack power =", warriorAttack);
        return("Archer attack power =", archerAttack);
    }

    function getArmor() virtual override view internal returns  (string , uint) {
        return("Base armor = ", armorBase);
        return("Warrior armor = ", armorWarrior);
        return("Archer armor = ", armorArcher);
    }


}    